export const ERRORS = {
    NOT_ADMIN: 'NotAdmin()',
    NOT_GOVERNANCE: 'NotGovernance()',
    TRANSFER_FAILED: 'TransferFailed()',
    NOT_MINER: 'NotMiner()',
    BLACKLIST_EXISTS: 'BlacklistExists()',
    BLACKLIST_NOT_EXISTS: 'BlacklistNotExists()',
    INVALID_MIN_GAS_TIP_CAP: 'InvalidMinGasTipCap()',
    INVALID_BASE_FEE: 'InvalidBaseFee()',
    INVALID_CANDIDATE_LIMIT: 'InvalidCandidateLimit()',
    SIDE_CALL_OT_ALLOWED: 'SideCallNotAllowed()',
    ONLY_EOA: 'OnlyEOA()',
    INSUFFICIENT_VALUE: 'InsufficientValue()',
    INVALID_SHARE_RATE: 'InvalidShareRate()',
    CANDIDATE_EXCEED_LIMIT: 'CandidateExceedLimit()',
    SAME_CANDIDATE: 'SameCandidate()',
    CANDIDATE_EXISTS: 'CandidateExists()',
    CANDIDATE_NOT_EXISTS: 'CandidateNotExists()',
    LEFT_NOT_CLAIMED: 'LeftNotClaimed()',
    CANDIDATE_WITHDRAW_NOT_ALLOWED: 'CandidateWithdrawNotAllowed()',
    MULTIPLE_VOTE_NOT_ALLOWED: 'MultipleVoteNotAllowed()',
    NO_VOTE: 'NoVote()',
};