name: Build

on:
  pull_request:
    branches:
      - bane-main
    types: [opened, synchronize]
    paths-ignore:
      - 'scripts/**'
      - '**/*.md'
  push:
    # Build for the bane-main branch.
    branches:
      - bane-main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build geth [default: latest bane-main; examples: v0.92.0, 0a4ff9d3e4a9ab432fd5812eb18c98e03b5a7432]'
        required: false
        default: ''

jobs:
  build_cli:
    name: Build geth and services
    runs-on: ${{matrix.os.name}}
    strategy:
      matrix:
        os: [{ name: ubuntu-20.04 }]
        arch: [amd64]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          # Allows to fetch all history for all branches and tags. Need this for proper versioning.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build geth
        run: make all
