name: Build

on:
  pull_request:
    branches:
      - bane-main
    types: [opened, synchronize]
    paths-ignore:
      - 'scripts/**'
      - '**/*.md'
  push:
    # Build for the bane-main branch.
    branches:
      - bane-main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build geth [default: latest bane-main; examples: v0.92.0, 0a4ff9d3e4a9ab432fd5812eb18c98e03b5a7432]'
        required: false
        default: ''

jobs:
  build_cli:
    name: Build geth and services
    runs-on: ${{matrix.os.name}}
    strategy:
      matrix:
        os: [{ name: ubuntu-22.04, bin-name: linux }]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          # Allows to fetch all history for all branches and tags. Need this for proper versioning.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build geth
        run: make all

      - name: Rename geth binary
        run: mv ./build/bin/geth* ./build/bin/geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}${{ (matrix.os.bin-name == 'windows' && '.exe') || '' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          path: ./build/bin/geth*
          if-no-files-found: error

      - name: Attach binary to the release as an asset
        if: ${{ github.event_name == 'release' }}
        run: gh release upload ${{ github.event.release.tag_name }} ./build/bin/geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}${{ (matrix.os.bin-name == 'windows' && '.exe') || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
